version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
     - 2020:8080
  postgres:
    container_name: postgres
    build: ./postgres/
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  pgadmin:
    container_name: pgadmin
    build: ./pgadmin/
    ports:
      - 80:80
    environment:
        PGADMIN_DEFAULT_EMAIL: postgres@test.de
        PGADMIN_DEFAULT_PASSWORD: postgres
    links:
      - postgres
    logging:
      driver: "none"
  kafka:
    container_name: kafka
    image: debezium/kafka:1.0
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - ADVERTISED_HOST_NAME=192.168.178.53
  connect:
    container_name: connect
    image: debezium/connect:1.0
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses